run:
  sample: 1000
  show_plot: true
  save_results: true
  logger: false

selection:
  drop_outliers_1: true
  drop_outliers_2: true
  nans_per_year_lt: 1
  nans_per_transect: .25
  flag_sandy: True,
  changerate_unc: None,
  no_sedcomp: True,
  low_detect_shlines: True,
  err_changerate: True,
  err_timespan: True