run:
  sample:
  show_plot: true
  save_results: true
  logLevel: "debug"
  filename: "sample"

selection:
  metadata:
    flag_sandy: true
    changerate_unc:
    no_sedcomp: true
    low_detect_shlines: true
    err_changerate: true
    err_timespan: true
  stats:
    drop_outliers_1: true
    drop_outliers_2: true
    nans_per_year_lt: 1
    nans_per_transect_lt: .25